spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:runfastdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath*:database/schema.sql
    data: classpath*:database/data.sql
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    generate-ddl: true
server:
  port: 8080